/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Todos: () => import('#controllers/todos_controller'),
}
